### ISSUE TITLE
further development (CRAN, documentation)

### ISSUE THREAD

**Issue by maxheld83** [hadley/bookdown#4]
I am very impressed by this toolchain, and I'd love to see (and help with) further development, if that's feasible.
I am a big fan of [rmarkdown](https://github.com/rstudio/rmarkdown), but I think it still lacks a facility for [long-form stuff](https://github.com/rstudio/rmarkdown/issues/387), like this book.

Bookdown seems to be (the first?) toolchain that builds *equally* high quality LaTeX *and* responsive HTML (via Jekyll) from an `Rmd` source, which is an incredible accomplishment that might just be another game changer for (academic) (open source) publishing.

(Gitbook.io may be another alternative, but I Jekyll might just be the better bet, because it's a bigger FOSS tent).

I'd love to help with this (if I can), I'm just not sure whether @hadley thinks this (bookdown) *might* be a suitable foundation for broader effort. Sure looks like it, but I'm no experienced enough, so I'd love some thoughts from @hadley and others.

Specifically:

- [ ] Does it make sense to start a documentation at this point?
- [ ] How far off is this from CRAN?
- [ ] Can this become an `rmarkdown` **format**? Or will it need to be its own package?
- [ ] Where is the chapter structure documented? (as in: this chapter comes first, then that – stupid, I know, just couldn't figure it out)
- [ ] How much work would it be to adequately support all the current features of `rmarkdown v2`, including, for example citations (#2) at the end of the book
- [ ] Broadly, is this a basis to build on for long-form publishing out of `Rmd`, or is gitbook.io or sth else a better platform after all?

**Comment by hadley** [comment]
In brief, bookdown was mostly an experiment. That experiment is now over, and I doubt bookdown will see much more development (although bits will show up elsewhere). In the future, I won't use jekyll. Instead I'd use a makefile to coordinate rebuilding individual chapters. Jekyll is just terrible at caching, and requires a lot of fairly painful rebuilding, and the whole ruby gem experience on travis is wonky.

**Comment by maxheld83** [comment]
great, thanks for the insight.

Any suggestions in which to go for long-form from `RMarkdown`, based on your experience?

`Rmd` -> `Md` (via RMarkdown/Knitr) -> `HTML5` (via something like gitbook.io)

Or some direct way?

`Rmd` -> `HTML5` ?

**Comment by hadley** [comment]
There's no doubt in my mind: Rmd -> md with knitr; md -> html/tex/epub with pandoc. Unless you actually want to sell your book, I don't see any benefit to gitbook.io.

**Comment by maxheld83** [comment]
mmh, I see.
No, I'm not into the gitbook.io marketplace – just like their templates.
That's the element (the templates) that would be missing from the pandoc toolchain, right?
That could all be accomplished within `Rmarkdown` then, right? Basically just another format and/or template.

**Comment by hadley** [comment]
There are plenty of other places to get templates - http://getpoole.com has a couple of nice ones which would be straightforward to adapt.

**Comment by maxheld83** [comment]
thanks so much for the insight and suggestions.
I hope to spend some time over the summer figuring out a nice RMarkdown + Pandoc setup.

**Comment by maxheld83** [comment]
just FYI: the discussion over at Jekyll about using it for book publishing is still [going strong](https://talk.jekyllrb.com/t/jekyll-template-support-for-academic-books/155).

**Comment by znmeb** [comment]
@hadley @maxheld83 

I'm coming in here a bit late, given that the issue is closed, but I'm planning on writing (and selling!) a book as well. So some notes:

1. "unless you actually want to sell your book" - there are other options besides GitBook. There's Amazon, of course, which requires MOBI format. That's easily done with either Amazon's proprietary "KindleGen" tool or open source "calibre".

    Gumroad: In fact, GitBook offloaded their "bookstore" operations to Gumroad a while back. I like Gumroad; they cater to indie authors and have great bundling options if you want to sell book/code/video packages.

   Leanpub: They have a nice store setup and also cater to indie authors and also support book/code/video bundles. They have their own Markdown toolchain which used to be awful but is now at least mostly acceptable. I wouldn't even be considering them, though, if they hadn't created a "bring your own book" option. If you choose this option you make the PDF, EPUB and MOBI files with your own toolchain and upload them to their store.

2. Every time I think about writing a lengthy book I come back to LyX. It's open source, has provisions for code chunks in R, has an outliner (a must-have for me) and has an unsurpassed LaTeX editing toolchain. 

    The downside of LyX is getting something other than a PDF out of it. With a little hacking you can make XHTML that can be converted to EPUB/MOBI but every time I've tried that, the outputs were ratty looking compared to the PDF.
